### ISSUE TITLE
Crashes on launch 

### ISSUE THREAD

**Issue by DjordjeMancic97** [rodydavis/easy_web_view#21]
Can't get this plugin to work, I'm testing it on Android 10. 

Code: 

```
EasyWebView(
              src: 'https://github.com/',
              isHtml: false,
              isMarkdown: false, onLoaded: () { 
                print('loaded');
               },
              
            )
```

Error : 
```
E/flutter ( 3200): [ERROR:flutter/lib/ui/ui_dart_state.cc(166)] Unhandled Exception: PlatformException(error, java.lang.IllegalStateException: Trying to create a platform view of unregistered type: plugins.flutter.io/webview
E/flutter ( 3200):      at io.flutter.plugin.platform.PlatformViewsController$1.createPlatformView(PlatformViewsController.java:97)
E/flutter ( 3200):      at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.create(PlatformViewsChannel.java:95)
E/flutter ( 3200):      at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.onMethodCall(PlatformViewsChannel.java:59)
E/flutter ( 3200):      at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:230)
E/flutter ( 3200):      at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/flutter ( 3200):      at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:658)
E/flutter ( 3200):      at android.os.MessageQueue.nativePollOnce(Native Method)
E/flutter ( 3200):      at android.os.MessageQueue.next(MessageQueue.java:336)
E/flutter ( 3200):      at android.os.Looper.loop(Looper.java:174)
E/flutter ( 3200):      at android.app.ActivityThread.main(ActivityThread.java:7397)
E/flutter ( 3200):      at java.lang.reflect.Method.invoke(Native Method)
E/flutter ( 3200):      at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
E/flutter ( 3200):      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:919)
E/flutter ( 3200): , null)
E/flutter ( 3200): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:570:7)
E/flutter ( 3200): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:159:18)
E/flutter ( 3200): <asynchronous suspension>
E/flutter ( 3200): #2      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:332:12)
E/flutter ( 3200): #3      AndroidViewController._create (package:flutter/src/services/platform_views.dart:634:54)
E/flutter ( 3200): #4      AndroidViewController.setSize (package:flutter/src/services/platform_views.dart:551:14)
E/flutter ( 3200): #5      RenderAndroidView._sizePlatformView (package:flutter/src/rendering/platform_view.dart:176:29)
E/flutter ( 3200): #6      RenderAndroidView.performResize (package:flutter/src/rendering/platform_view.dart:157:5)
E/flutter ( 3200): #7      RenderObject.layout (package:flutter/src/rendering/object.dart:1746:9)
E/flutter ( 3200): #8      RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:113:13)
E/flutter ( 3200): #9      RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
E/flutter ( 3200): #10     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:113:13)
E/flutter ( 3200): #11     RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
E/flutter ( 3200): #12     RenderConstrainedBox.performLayout (package:flutter/src/rendering/proxy_box.dart:268:13)
E/flutter ( 3200): #13     RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
E/flutter ( 3200): #14     _RenderLayoutBuilder.performLayout (package:flutter/src/widgets/layout_builder.dart:299:13)
E/flutter ( 3200): #15     RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
E/flutter ( 3200): #16     RenderPadding.performLayout (package:flutter/src/rendering/shifted_box.dart:207:11)
E/flutter ( 3200): #17     RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
E/flutter ( 3200): #18     RenderPadding.performLayout (package:flutter/src/rendering/shifted_box.dart:207:11)
E/flutter ( 3200): #19     RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
E/flutter ( 3200): #20     MultiChildLayoutDelegate.layoutChild (package:flutter/src/rendering/custom_layout.dart:171:11)
E/flutter ( 3200): #21     _ScaffoldLayout.performLayout (package:flutter/src/material/scaffold.dart:480:7)
E/flutter ( 3200): #22     MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart:240:7)
E/flutter ( 3200): #23     RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:399:14)
E/flutter ( 3200): #24     RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
E/flutter ( 3200): #25     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:113:13)
E/flutter ( 3200): #26     RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
E/flutter ( 3200): #27     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:113:13)
E/flutter ( 3200): #28     _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1267:11)
E/flutter ( 3200): #29     RenderObject.layout (package:flutter/src/rendering/object.dart:1767:7)
E/flutter ( 3200): #30     RenderProxyBoxMixin.performLa
```

**Comment by rodydavis** [comment]
You need to follow the set up as described here: https://pub.dev/packages/webview_flutter
